name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, review_requested]

jobs:
  test:
    uses: 96daysleft/github-workflows/.github/workflows/vscode-pr-check.yml@v1
    with:
      run-pr-agent: true
    secrets: inherit
