name: Pull Request Check

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review, review_requested]

permissions:
  contents: read

jobs:
  test:
    uses: 96daysleft/github-workflows/.github/workflows/vscode-pr-check.yml@release
    with:
      run-pr-agent: true
    secrets: inherit
