name: Publish to VSCode Marketplace

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write      # required for keyless signing
  attestations: write  # required to publish attestation

jobs:
  buildpublish-vscode:
    env:
      EXTENSION_NAME: casechanger.vsix
      SBOM_NAME: sbom.cdx.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Run compile
        run: npm run compile

      - name: Package extnesion
        run: npc vsce package --out ${EXTENSION_NAME}

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: cyclonedx-json
          output-file: ${SBOM_NAME}

      - name: Attest SBOM
        uses: actions/attest-sbom@v2
        with:
          subject-path: ${EXTENSION_NAME}
          sbom-path: ${SBOM_NAME}

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: ${EXTENSION_NAME}

      - name: Publish to VS Code Marketplace
        run: npx vsce publish --packagePath ${EXTENSION_NAME} -p ${{ secrets.VSCE_PAT }}

      - name: Publish to Open VSX
        run: npx ovsx publish ${EXTENSION_NAME} -p ${{ secrets.OVSX_PAT }}
          

      - name: Create GitHub Release with assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${EXTENSION_NAME}
            ${SBOM_NAME}