name: Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag whose .vsix asset should be published'
        required: true
        type: string

permissions:
  contents: read  # download release assets

jobs:
  publish:
    uses: 96daysleft/github-workflows/.github/workflows/vscode-ext-publish.yml@release
    with:
      tag: ${{ inputs.tag }}
      extension-name: casechanger.vsix
      publish-vsce: ${{ vars.PUBLISH_VSCE }}
      publish-vsx: ${{ vars.PUBLISH_VSX }}
    secrets:
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
      OVSX_PAT: ${{ secrets.OVSX_PAT }}
