name: Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        type: choice
        description: 'The type of version to increment: major, minor, or patch'
        required: true
        options:
          - patch
          - minor
          - major

permissions: write-all

jobs:
  release:
    uses: 96daysleft/github-workflows/.github/workflows/vscode-ext-release.yml@v1
    with:
      version-type: ${{ inputs.version_type }}
      extension-name: casechanger.vsix
      publish-vsce: ${{ vars.PUBLISH_VSCE }}
      publish-vsx: ${{ vars.PUBLISH_VSX }}
    secrets:
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
      OVSX_PAT: ${{ secrets.OVSX_PAT }}
